"""Original 56 LULC codes, 2024 edition user guide pp. 27–56; 0 is unknown."""
LEGEND = {str(k): v for k, v in {
    0: "Unknown", 10: "Tidal Waters", 11: "Lakes and Reservoirs", 12: "Riverine Ponds",
    13: "Terrene Ponds", 14: "Streams and Rivers", 15: "Bare Shore", 20: "Roads",
    21: "Structures", 22: "Other Impervious", 23: "Tree Canopy over Roads",
    24: "Tree Canopy over Structures", 25: "Tree Canopy over Impervious",
    26: "Tree Canopy over Turf Grass", 27: "Turf Grass", 28: "Bare Developed",
    30: "Extractive Barren", 31: "Extractive Impervious", 32: "Solar Field Panel Arrays",
    33: "Solar Field Barren", 34: "Solar Field Herbaceous", 35: "Solar Field Shrubland",
    36: "Suspended Succession Barren", 37: "Suspended Succession Herbaceous",
    38: "Suspended Succession Shrubland", 40: "Forest", 41: "Forested Other",
    42: "Natural Succession Barren", 43: "Natural Succession Herbaceous",
    44: "Natural Succession Shrubland", 45: "Harvested Forest Barren",
    46: "Harvested Forest Herbaceous", 50: "Riverine Wetlands Non-forested Barren",
    51: "Riverine Wetlands Non-forested Herbaceous", 52: "Riverine Wetlands Non-forested Shrubland",
    53: "Riverine Wetlands Forested Other", 54: "Riverine Wetlands Forest",
    55: "Riverine Wetlands Harvested Forest", 60: "Terrene Wetlands Barren",
    61: "Terrene Wetlands Herbaceous", 62: "Terrene Wetlands Shrubland",
    63: "Terrene Wetlands Forested Other", 64: "Terrene Wetlands Forest",
    65: "Terrene Wetlands Harvested Forest", 70: "Tidal Wetlands Barren",
    71: "Tidal Wetlands Herbaceous", 72: "Tidal Wetlands Shrubland",
    73: "Tidal Wetlands Forested Other", 74: "Tidal Wetlands Forest",
    75: "Tidal Wetlands Harvested Forest", 80: "Cropland Barren", 81: "Cropland Herbaceous",
    82: "Orchards and Vineyards Barren", 83: "Orchards and Vineyards Herbaceous",
    84: "Orchards and Vineyards Shrubland", 85: "Pasture and Hay Barren",
    86: "Pasture and Hay Herbaceous",
}.items()}
