import { test, expect } from "@playwright/test";

test("requester → operator → local agent → flight → return → landed → complete", async ({ browser }) => {
  const requester = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const operator = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const request = await requester.newPage(), dispatch = await operator.newPage();
  const errors: string[] = [];
  for (const page of [request, dispatch]) page.on("pageerror", error => errors.push(error.message));
  await Promise.all([request.goto("/request"), dispatch.goto("/operator")]);
  const description = `Demo grounds inspection ${Date.now()}`;
  await request.getByLabel("Your name").fill("Alex Morgan");
  await request.getByLabel("Job description").fill(description);
  await request.getByRole("button", { name: "Submit job" }).click();
  await expect(request.getByText("Your job is with the operator.", { exact: false })).toBeVisible();
  await dispatch.getByRole("button").filter({ hasText: description }).click();
  const accept = dispatch.getByRole("button", { name: "Accept & assign simulator" });
  await expect(accept).toBeDisabled();
  await dispatch.getByRole("checkbox", { name: "Supervised autonomy" }).check();
  await accept.click();
  const start = dispatch.getByRole("button", { name: "Start autonomous flight" });
  await expect(start).toBeEnabled({ timeout: 15000 });
  await dispatch.screenshot({ path: "test-results/operator-ready.png", fullPage: true });
  await start.click();
  await expect(dispatch.getByRole("button", { name: "Flight in progress" })).toBeDisabled();
  await expect(dispatch.getByTestId("altitude")).not.toHaveText("0m", { timeout: 5000 });
  await expect.poll(async () => Number(await dispatch.getByTestId("drone-marker").getAttribute("data-y"))).toBeLessThan(360);
  await dispatch.screenshot({ path: "test-results/operator-flying.png", fullPage: true });
  await expect(dispatch.getByRole("heading", { name: "Returning to launch" })).toBeVisible({ timeout: 15000 });
  await dispatch.screenshot({ path: "test-results/operator-returning.png", fullPage: true });
  await expect(dispatch.getByRole("heading", { name: "Mission completed", exact: true })).toBeVisible({ timeout: 15000 });
  await expect(request.getByRole("heading", { name: "Mission completed", exact: true })).toBeVisible();
  await expect(dispatch.getByTestId("altitude")).toHaveText("0m");
  await expect(dispatch.getByTestId("elapsed")).toHaveText("20.0/ 20 s");
  await expect(dispatch.getByTestId("drone-marker")).toHaveAttribute("data-x", "100");
  await expect(dispatch.getByTestId("drone-marker")).toHaveAttribute("data-y", "360");
  await dispatch.getByText("Mission activity", { exact: false }).click();
  const events = await dispatch.locator(".events li").allTextContents();
  expect(events.filter(e => e.includes("Start accepted"))).toHaveLength(1);
  expect(events.at(-2)).toContain("Landed at launch · altitude 0 m");
  expect(events.at(-1)).toContain("Mission completed");
  await Promise.all([request.reload(), dispatch.reload()]);
  await expect(request.getByRole("heading", { name: "Mission completed", exact: true })).toBeVisible();
  await expect(dispatch.getByRole("heading", { name: "Mission completed", exact: true })).toBeVisible();
  await dispatch.screenshot({ path: "test-results/operator-completed.png", fullPage: true });
  await request.setViewportSize({ width: 390, height: 844 });
  await request.screenshot({ path: "test-results/requester-mobile.png", fullPage: true });
  expect(await request.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  await requester.close(); await operator.close();
});
