import { test, expect } from "@playwright/test";
import { saveOperatorLocations } from "./locations";

test("an operator registers physical drone specifications without a join code", async ({ page }, info) => {
  if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(process.env.NEXT_PUBLIC_CONVEX_URL ?? "")) throw new Error("Registration verification requires the local backend.");
  const suffix = Date.now();
  await page.goto("/operator");
  await page.getByRole("button", { name: "Create an account", exact: true }).click();
  await page.getByLabel("Email", { exact: true }).fill(`registration-${suffix}@iris.test`);
  await page.getByLabel("Password", { exact: true }).fill(`Registration-${suffix}-secure`);
  await page.getByRole("button", { name: "Create account", exact: false }).click();
  await page.getByLabel("Your name", { exact: true }).fill("New Operator");
  await page.getByRole("radio", { name: /Operator/ }).check();
  await page.getByRole("button", { name: "Open workspace", exact: true }).click();
  await expect(page.getByLabel("Invitation code")).toHaveCount(0);
  await saveOperatorLocations(page);
  await page.getByRole("link", { name: "Fleet", exact: true }).click();
  await page.getByRole("button", { name: "Add aircraft", exact: true }).click();
  await page.getByLabel("Drone type").selectOption("High-Resolution Camera Drone");
  await page.getByRole("button", { name: "Payload", exact: true }).click();
  await page.getByLabel("Maximum payload (kg)").fill("1.5");
  await page.getByLabel("Max range (m)").fill("6500");
  const name = (await page.getByTestId("generated-name").inputValue()).trim();
  await page.getByRole("button", { name: "Register aircraft", exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Hide credential", exact: true }).click();
  await page.reload();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  await expect(page.getByText("High-Resolution Camera Drone", { exact: false })).toBeVisible();
  await expect(page.getByText("Payload capacity: 1.5 kg", { exact: false })).toBeVisible();
  await expect(page.getByText("Offline", { exact: true })).toBeVisible();
  await page.screenshot({ path: info.outputPath("registered-drone.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("registered-drone-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.getByRole("button", { name: `Remove ${name}` }).click();
  await expect(page.getByRole("heading", { name: "Remove aircraft", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toBeVisible();
  await page.getByRole("button", { name: `Remove ${name}` }).click();
  await page.getByRole("button", { name: "Remove", exact: true }).click();
  await expect(page.getByRole("heading", { name, exact: true })).toHaveCount(0);
});
