import { test, expect } from "@playwright/test";

test("an operator registers physical drone specifications without a join code", async ({ page }, info) => {
  if (!/^http:\/\/127\.0\.0\.1:\d+$/.test(process.env.NEXT_PUBLIC_CONVEX_URL ?? "")) throw new Error("Registration verification requires the local backend.");
  const suffix = Date.now();
  await page.goto("/operator");
  await page.getByRole("button", { name: "Create an account", exact: true }).click();
  await page.getByLabel("Email", { exact: true }).fill(`registration-${suffix}@zip.test`);
  await page.getByLabel("Password", { exact: true }).fill(`Registration-${suffix}-secure`);
  await page.getByRole("button", { name: "Create account", exact: false }).click();
  await page.getByLabel("Your name", { exact: true }).fill("New Operator");
  await page.getByRole("button", { name: "Open workspace", exact: true }).click();
  await expect(page.getByLabel("Invitation code")).toHaveCount(0);
  await page.getByRole("link", { name: "Register your drone" }).click();
  await page.getByLabel("Name", { exact: true }).fill(`Survey drone ${suffix}`);
  await page.getByLabel("Drone model").fill("Custom camera aircraft");
  await page.getByLabel("Hardware identity").fill(`survey-${suffix}`);
  await page.getByLabel("Camera", { exact: true }).check();
  await page.getByLabel("Payload carrying", { exact: true }).check();
  await page.getByLabel("Maximum payload (kg)").fill("1.5");
  await page.getByLabel("Service radius (m)").fill("6500");
  await page.getByRole("button", { name: "Register aircraft", exact: true }).click();
  await expect(page.getByRole("heading", { name: `Survey drone ${suffix}`, exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Hide credential", exact: true }).click();
  await page.reload();
  await expect(page.getByRole("heading", { name: `Survey drone ${suffix}`, exact: true })).toBeVisible();
  await expect(page.getByText("Custom camera aircraft", { exact: false })).toBeVisible();
  await expect(page.getByText("Payload capacity: 1.5 kg", { exact: false })).toBeVisible();
  await expect(page.getByText("Registered · connection required", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Accepting new jobs")).toBeChecked();
  await page.screenshot({ path: info.outputPath("registered-drone.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("registered-drone-mobile.png"), fullPage: true });
});
