"use client";
import { useState } from "react";
import { useAction, useMutation, useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { AuthGate, type Account } from "./auth-gate";
import { AppShell } from "./app-shell";
import { INITIAL_LOCATION, messageOf } from "./production-workspace";
import type { Capability, Environment } from "@/lib/operations";

export function FleetWorkspace() { return <AuthGate>{account => <AppShell account={account} surface="fleet"><Fleet account={account} /></AppShell>}</AuthGate>; }
function Fleet({ account }: { account: Account }) {
  const vehicles = useQuery(api.fleet.mine, account.operator?.approved ? {} : "skip");
  const register = useMutation(api.fleet.register), revoke = useMutation(api.fleet.revokeCredentials), availability = useMutation(api.accounts.updateAvailability);
  const issue = useAction(api.credentials.issueAgentCredential);
  const [environment, setEnvironment] = useState<Environment>("aircraft"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [credential, setCredential] = useState<{ vehicleId: string; token: string } | null>(null);
  async function provision(vehicleId: Id<"vehicles">) { setBusy(true); setError(""); try { const result = await issue({ vehicleId }); setCredential({ vehicleId, token: result.token }); } catch (error) { setError(messageOf(error)); } finally { setBusy(false); } }
  return <main className="workspace"><div className="page-heading"><div><p className="eyebrow">OPERATOR EQUIPMENT</p><h1>Aircraft & connections</h1></div><label className="mode-choice compact"><input type="checkbox" disabled={!account.operator?.approved} checked={account.operator?.acceptingJobs ?? false} onChange={async e => { try { await availability({ acceptingJobs: e.target.checked }); } catch (error) { setError(messageOf(error)); } }} /><span>Accepting new jobs</span></label></div>
    {error && <p className="error" role="alert">{error}</p>}<div className="layout"><aside className="sidebar"><section className="panel"><h2>Register an aircraft</h2><form onSubmit={async event => { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(""); try {
      const capabilities: Capability[] = environment === "simulated" ? ["takeoff", "hover", "land", "position", "autonomous", "manual_remote", "manual_computer"] : data.getAll("capabilities") as Capability[];
      const vehicleId = await register({ name: String(data.get("name")), hardwareId: String(data.get("hardwareId")), environment, capabilities, model: String(data.get("model") ?? ""), serviceRadiusM: Number(data.get("serviceRadius")), maxPayloadKg: environment === "simulated" ? 0 : Number(data.get("payload")), home: { lat: Number(data.get("lat")), lon: Number(data.get("lon")) }, maxRadiusM: Number(data.get("radius")) });
      const result = await issue({ vehicleId }); setCredential({ vehicleId, token: result.token });
    } catch (error) { setError(messageOf(error)); } finally { setBusy(false); } }}><label>Name<input name="name" required maxLength={80} placeholder="e.g. Training aircraft 01" /></label><label>Drone model<input name="model" maxLength={100} placeholder="Manufacturer and model" /></label><label>Hardware identity<input name="hardwareId" required pattern="[a-zA-Z0-9_-]{3,80}" placeholder="zip-sim-01" /></label><label>Environment<select aria-label="Environment" value={environment} onChange={e => setEnvironment(e.target.value as Environment)}><option value="simulated">Local simulator</option><option value="aircraft">Physical aircraft — integration required</option></select></label><div className="coordinates"><label>Launch latitude<input name="lat" type="number" step="any" min={-90} max={90} defaultValue={account.operator?.base.lat ?? INITIAL_LOCATION.lat} required /></label><label>Launch longitude<input name="lon" type="number" step="any" min={-180} max={180} defaultValue={account.operator?.base.lon ?? INITIAL_LOCATION.lon} required /></label></div><label>Flight boundary radius (m)<input name="radius" type="number" min={5} max={3000} defaultValue={100} required /></label><label>Service radius (m)<input name="serviceRadius" type="number" min={100} max={100000} defaultValue={account.operator?.serviceRadiusM ?? 5000} required /></label>{environment === "aircraft" && <><fieldset><legend>Supported capabilities</legend>{([ ["takeoff", "Takeoff"], ["hover", "Hover"], ["land", "Landing"], ["position", "Position telemetry"], ["autonomous", "Autonomous control"], ["manual_remote", "Remote control"], ["manual_computer", "Computer control"], ["camera", "Camera"], ["payload", "Payload carrying"] ] as const).map(([value, label]) => <label className="mode-choice compact" key={value}><input type="checkbox" name="capabilities" value={value} defaultChecked={["takeoff", "hover", "land", "manual_remote"].includes(value)} /><span>{label}</span></label>)}</fieldset><label>Maximum payload (kg)<input name="payload" type="number" min={0} max={25} step={.1} defaultValue={0} required /></label></>}<p className="muted">{environment === "simulated" ? "The simulator supports flight checks and control handoff. It does not provide a camera or carry a payload." : "Physical control remains disabled until an administrator verifies the adapter and capabilities."}</p><button className="primary" disabled={busy}>{busy ? "Registering…" : "Register aircraft"}</button></form></section></aside>
    <div className="main-column">{(vehicles?.length ?? 0) === 0 && <section className="panel"><h2>No aircraft registered</h2><p className="muted">Register your first aircraft, provision a connection credential, and start its local flight agent.</p></section>}{vehicles?.map(vehicle => <section className="panel" key={vehicle._id}><div className="mission-heading"><div><p className="eyebrow">{vehicle.environment === "simulated" ? "SIMULATOR" : "PHYSICAL AIRCRAFT"}</p><h2>{vehicle.name}</h2></div><span className="status">{vehicle.activeOperationId ? "Assigned" : vehicle.integrationApproved ? "Available for dispatch" : "Registered · connection required"}</span></div><p className="muted">{vehicle.model ? `${vehicle.model} · ` : ""}{vehicle.hardwareId} · {vehicle.home.lat.toFixed(6)}, {vehicle.home.lon.toFixed(6)} · {vehicle.maxRadiusM} m boundary</p><p className="muted">Capabilities: {vehicle.capabilities.map(capability => capability.replaceAll("_", " ")).join(", ")} · Payload capacity: {vehicle.maxPayloadKg} kg</p><p className="muted">{vehicle.telemetry ? `Latest measurement: ${new Date(vehicle.telemetry.sample.capturedAt).toLocaleTimeString()} · battery ${vehicle.telemetry.sample.batteryPct?.toFixed(0) ?? "unknown"}%` : "No aircraft measurements received."}</p><div className="interventions"><button disabled={busy || !!vehicle.activeOperationId} onClick={() => void provision(vehicle._id)}>Issue / rotate agent credential</button><button className="land-button" onClick={async () => { setError(""); try { await revoke({ vehicleId: vehicle._id }); setCredential(null); } catch (error) { setError(messageOf(error)); } }}>Revoke agent access</button></div>
      {credential?.vehicleId === vehicle._id && <div className="credential-box"><h3>Connect the local flight agent</h3><p className="muted">Save this credential in <code>.env.agent</code> on the operator computer, then run <code>npm run agent</code>. The credential is shown only now.</p><pre className="secret-value">ZIP_AGENT_TOKEN={credential.token}</pre><button onClick={() => void navigator.clipboard.writeText(`ZIP_AGENT_TOKEN=${credential.token}`)}>Copy agent configuration</button><button className="text-button" onClick={() => setCredential(null)}>Hide credential</button></div>}
    </section>)}
    </div></div></main>;
}
